Neos:
  Neos:
    fusion:
      autoInclude:
        'UpAssist.NodeTypes.Gallery': true
    userInterface:
      translation:
        autoInclude:
          'UpAssist.NodeTypes.Gallery':
            - 'NodeTypes/*'
            - Main
